name: Checkout Test
on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - name: show list
        run: ls -al
      - name: show workflow yml file
        run: cat .github/workflows/checkout.yml


