name: Checkout Test
on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: dev_dir
          key: ${{ runner.os }}-dev-${{ hashFiles('dev_dir') }}
      - runs: ls -al dev_dir
      - uses: actions/checkout@v3
        with:
          ref: dev
          path: dev_dir




